FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /workspace
COPY pom.xml .
RUN mvn -B -DskipTests dependency:go-offline
COPY src ./src
RUN mvn -B -DskipTests package

FROM eclipse-temurin:21-jre

WORKDIR /app
ENV JAVA_OPTS=""
COPY --from=build /workspace/target/*.jar /app/app.jar
EXPOSE 8122

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
